version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pa55w0rd
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    container_name: SQLserver-2019
